### PR TITLE
patch fix & feature

### PR DESCRIPTION
**Pull request by nucleargen**
fixed compatibility with Factorio 0.13.10+
transport chest speed now consider with chest entity tilesize (actual for warehousing addon, multiplies speed by 9 or 36)

### CODE REVIEW

**Comment by Simcra** [comment]
Yeah, a few things here need discussion. I have a lot of unpushed changes locally at the moment, warehousing addon was a test prototype, could you explain what was wrong with it?

**Comment by nucleargen** [comment]
Without changing item speed transportation warehousing chests looks similar as vanilla chests and gives only inserters count access advantage.
Warehousing chests is much bigger than vanilla chests and therefore have bigger "channel" to transport items.
Multiplier value is a subject of discussion. I've depend it on raw entity tilesize:
for vanilla chests it is 1, for storehouses it is 9 and for warehouses - 36.
So, building warehouse now is similar as building 36 iron chests, but in 1 entity.

**Comment by Simcra** [comment]
Not a bad idea, just needs a little balancing. What do you think would be reasonable?

**Comment by Simcra** [comment]
perhaps something like 3x for storehouses and 12x for warehouses?

**Comment by nucleargen** [comment]
May be.
Or 8x and 20x - count of normal inserters can be connected to.

```
XXX
XOX
XXX

XXXXXX
XOOOOX
XOOOOX
XOOOOX
XOOOOX
XXXXXX
```

**Comment by Simcra** [comment]
Yep, that'll work. Just remember the config vars, they'll significantly increase the transfer speed of transport chests if we go with this ideology. Lastly, with the paired entities thing, the 0 radius was intentional but if you think it would be better to have a 1 radius that's fine too.

**Comment by nucleargen** [comment]
How I've understand API changes and throwed exceptions - radius of 0 doesn't work anymore in find_entity.

**Comment by Simcra** [comment]
radius is a bit of a different thing with the paired entities, it's used for clearing the ground. The function can be found in pair-util, I will pull your changes and push my changes.

**Pull request merged**
